### ISSUE TITLE
Cannot import blueprint

### ISSUE THREAD

**Issue by tiennou** [screepers/screeps-tools#3]
Using the JSON Import/Export window, as soon as the text value changes it gets reset to the default blank slate, so you cannot paste your blueprint in

**Comment by tiennou** [comment]
Did a few more tests after cloning and building locally, which seems to be a different version than the one deployed.

Blueprint: https://github.com/bencbartlett/Overmind/blob/master/assets/basePlanner/bunker_layout.txt

Pasting blueprint:
```
Imported JSON:
building-planner.tsx:274 {name: '', shard: 'shard0', rcl: 8, buildings: {…}}
building-planner.tsx:287 Uncaught TypeError: Cannot read properties of undefined (reading 'plain')
    at building-planner.tsx:287:26
    at Array.forEach (<anonymous>)
    at mx.importJson (building-planner.tsx:286:43)
    at ob.importJson (modal-json.tsx:34:28)
    at onChange (modal-json.tsx:61:62)
    at Object.st (react-dom.production.min.js:52:317)
    at pt (react-dom.production.min.js:52:471)
    at react-dom.production.min.js:53:35
    at Br (react-dom.production.min.js:100:68)
    at Wr (react-dom.production.min.js:101:380)

```

Entering a comma to edit the blueprint manually:
```
modal-json.tsx:33 Uncaught SyntaxError: Expected double-quoted property name in JSON at position 45
    at JSON.parse (<anonymous>)
    at ob.importJson (modal-json.tsx:33:29)
    at onChange (modal-json.tsx:61:62)
    at Object.st (react-dom.production.min.js:52:317)
    at pt (react-dom.production.min.js:52:471)
    at react-dom.production.min.js:53:35
    at Br (react-dom.production.min.js:100:68)
    at Wr (react-dom.production.min.js:101:380)
    at react-dom.production.min.js:113:65
    at et (react-dom.production.min.js:292:189)
[snip]
```
